### ISSUE TITLE
Fails to build due to missing documentation.

### ISSUE THREAD

**Issue by yuvallanger** [nebgnahz/cv-rs#101]
Running `cargo build` fails due to a [`#![deny(missing_docs)]`](https://github.com/nebgnahz/cv-rs/blob/master/src/lib.rs#L10) and missing documentation in two `macro_rules!` definitions - [`path_to_cstring`](https://github.com/nebgnahz/cv-rs/blob/master/src/text/macros.rs#L2) and [`string_to_cstring`](https://github.com/nebgnahz/cv-rs/blob/master/src/text/macros.rs#L15).

**Comment by Pzixel** [comment]
Thank you.

Fix is coming ;)
