### ISSUE TITLE
Move example code to documentation

### ISSUE THREAD

**Issue by nebgnahz** [nebgnahz/cv-rs#15]
Well, after so long time, I don't remember how to use this library any more... examples are exceptionally helpful

**Comment by Restioson** [comment]
Cv-s "in the wild" links could be useful here.

**Comment by Pzixel** [comment]
I'm not sure we need this issue open. It doesn't serve any purpose except for producing some guilt "oh no, another month has gone and I still didn't move example code to documentation". I mean you have to choose if you actually planning to do it or you have others priorities, then pause it 😃

**Comment by nebgnahz** [comment]
@Pzixel, Good point! The guilt has lasted for almost a year :)
