### ISSUE TITLE
Issue installing under Windows

### ISSUE THREAD

**Issue by Restioson** [nebgnahz/cv-rs#16]
Hi! I've been having a bit of trouble installing `cv-rs` under Windows. I have followed the OpenCV installation tutorial (using downloaded binaries), and have tested it (and found it working) with Python (2.7). I've added basically all the directories inside of the opencv dir, including the ones in `x64` to `PATH`, yet it still seems like the compiler is missing `opencv2\core.hpp` :/ Any help would be appreciated!

---
[Full error/build log](https://gist.github.com/Restioson/31be55c41b41ea643bb0dbfd59642109)

**Comment by nebgnahz** [comment]
Ah, I've never tried this on Windows (and for now, I don't have a Window to test).

Basically this binding uses `gcc` to build a thin wrapper around OpenCV for Rust. To build the wrapper, this line (https://github.com/nebgnahz/cv-rs/blob/master/build.rs#L9) configures the include path.

On Linux and OS X, the following include path works.

```rust
        .include("/usr/local/include")
```

For Windows, change that line to the corresponding path so that `opencv2\core.hpp` can be located. According to [this tutorial](http://www.learnopencv.com/install-opencv3-on-windows/), it might be `C:/Users/Vaibhaw Chandel/Documents/opencv-3.2.0` or something similar.

**Comment by Restioson** [comment]
OK, I'll try this and get back to you.

**Comment by Restioson** [comment]
@nebgnahz PR which fixes it (at least on _my_ machine :) ) #17

**Comment by nebgnahz** [comment]
@Restioson I tried to set up CI for Windows and encountered some problem regarding `lib` and `dll`. The project can build, but it cannot test or run.

I updated the [build script](https://github.com/nebgnahz/cv-rs/blob/master/build.rs#L14) and [README.md](https://github.com/nebgnahz/cv-rs/blob/master/README.md) to reflect the changes. They are available in master branch and from now on, AppVeyor will reports Windows building status. Give it a short and let me know if this runs on Windows or not.

**Comment by Restioson** [comment]
@nebgnahz it compiles. I didn't test to see if it actually worked since I was sick yesterday and didn't really feel up to it, but I can try... I'll get back to you hopefully today

**Comment by Restioson** [comment]
@nebgnahz so what's the story? I'm going to be trying to get this to work on Windows again soon hopefully, time permitting.

**Comment by Pzixel** [comment]
@Restioson it's always working on windows, both msvc and mingw. Please, see most recent commits and readme.

**Comment by Restioson** [comment]
Is it? Nice. At my last check according to nebgnahz it wasn't so I wanted to get back up to date. Cool!

**Comment by Pzixel** [comment]
Yep. At this moment, installation on Windows is as easy as run one powershell script. We was fighting with CI servers a lot, but it worth it.

**Comment by nebgnahz** [comment]
@Restioson Yes, @Pzixel has helped extensively setting up Windows build script and build testing on AppVeyor. Give it a shot and let us know how it works.

**Comment by Restioson** [comment]
Nice! Thanks

**Comment by Restioson** [comment]
It appears I'm still getting issues building. 

[Build Log](https://gist.github.com/Restioson/35e29e8dcf246f0dd35ba693c9ab2b5d)
[Erroring Line Output (run from cmd)](https://gist.github.com/Restioson/a1c97d846bdd93cc16ce166e2ace5f7f)

**Comment by Pzixel** [comment]
It seems that you are using prebuilt `vc14_vc15` opencv. It wont' work. You have to run script that builds and configures OpenCV from scratch.

**Comment by Restioson** [comment]
@Pzixel on a slightly unrelated note, the readme install guide specifies that you must "Copy files from .windows folder there [C:\opencv]". Which `.windows` folder is meant?

**Comment by Pzixel** [comment]
@Restioson there is a `.windows` folder in repository.

**Comment by Restioson** [comment]
@pzixel ah OK. Maybe it should be mentioned in the readme...

**Comment by Pzixel** [comment]
I thought it's obvious. Because it's not a common folder. If someone else would ask the same thing I'l fix it. For now I think it's ok as it is.

**Comment by Restioson** [comment]
I thought that it referred to either: 1) Some .Windows folder in C:\, 2) Some .Windows folder in opencv sources, or 3) Some .Windows folder in cmake

**Comment by nebgnahz** [comment]
@Pzixel  I think it doesn't harm to make it explicit in the README.

Also, we should support easy binding to OCV on Windows without building from the source. Something like [this instruction](https://github.com/Pzixel/cv-rs/blob/9f4b609d286df11ae13a31de012f917d6cf01360/README.md#for-installation-without-cuda). Yes, one loses CUDA support in this case; but the build process is much simpler.

**Comment by Pzixel** [comment]
It's not possible to build cv-rs without sources because we it require `xfeatures2d` to be compiled. If you find any way to do it, please contact us. But currently it's not possible.

**Comment by nebgnahz** [comment]
perhaps refactor it into features .

**Comment by Pzixel** [comment]
I don't think it's nesessary Prebuild opencv is quite limited. And it's building don't takes a lot of time: half of an hour or something... And it takes only once.

**Comment by Restioson** [comment]
Half an hour *is* quite a long time. Perhaps it could be automatically built from source or something? Or perhaps a tool to install and build opencv

**Comment by Pzixel** [comment]
It can't.

**Comment by nebgnahz** [comment]
P.S. @Restioson If you are still experiencing build issues, please open this issue so that we know it's un-resolved. If you have successfully built it following the instructions on README for now, then leave this as closed.

**Comment by Pzixel** [comment]
I don't think `opencv` is useful without `opencv-contrib` features. It's also limiting `cuda` features. Prebuilt image is quite pleasant, however it's very limiting. We can split features on `prebuilt/nonprebuilt` features, but it still consufing, especially for non-windows users. SIFT/SURF requires `opencv_contrib` and they are most demanded features. Our instruction is already using fact that user knows nothing but `click this script and you are fine`. It doesn't matter how many couple of cups he drunk, he just click and do it stuff, then it come back and everything is configured. It's much easier than our old instruction, and it cover all possible variants with compiled openc_contrib/cuda/whatever.

**Comment by Restioson** [comment]
@nebgnahz I haven't had a chance to finish the readme steps but I will get back to you when I have.

**Comment by Pzixel** [comment]
@nebgnahz I'd rather prefer better instruction for `linux` installation. There is a lot of `apt-get` packages in `travis.yml` that aren't mentioned in readme at all :)
