### ISSUE TITLE
Tested with opencv 3.3.1, Most tests pass

### ISSUE THREAD

**Issue by greenpdx** [nebgnahz/cv-rs#22]
I have just tested master with opencv 3.3.1 compiled on ubuntu 17:10.  
The result is as follows.  What other tests can I run to test if it is working?

     Running target/debug/deps/utils-17eb4cc117ed80f3

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests cv

running 1 test
test src/core.rs - core::Mat::from_buffer (line 332) ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

**Comment by nebgnahz** [comment]
I usually just do `cargo test` in the root directory. And frankly there hasn't been many tests because most of the implementations are wrappers.

**Comment by greenpdx** [comment]
I did that,  I also ran the examples and they worked.  I may try to add Dnn and ml.
