### ISSUE TITLE
Always support latest OpenCV native libraries

### ISSUE THREAD

**Issue by Pzixel** [nebgnahz/cv-rs#25]
Currently we have to do commits like this just to make wrappers work each OpenCV release: https://github.com/nebgnahz/cv-rs/commit/160d926353a7b1cfc63993b9ea42a8f03265cade .

I suppose we'd better to search for the name automatically. For example:

```rust
#[cfg(windows)]
fn opencv_link() {
    if let Ok(dir) = std::env::var("OPENCV_LIB") && let Some(opencv_world) = get_opencv_world(&dir) {
        println!("cargo:rustc-link-search=native={}", dir);
        println!("cargo:rustc-link-lib={}", opencv_world);
    } else {
        eprint!("%OPENCV_DIR% is not set properly.");
        std::process::exit(0x0100);
    }
}
```

Because I have currently `opencv_world340` and it obviosly not working. I imagine `get_opencv_world` returns file that is named like starts with `opencv_world`, and take one that doesn't have `d` in the end.

I can write the pull request myself in few days if you agree with this proposal.

**Comment by nebgnahz** [comment]
That sounds reasonable. Thanks for the contribution.

*I am not extremely familiar with OpenCV installation on Windows. Is it common to have (and use) `opencv_worldxxx.dll`? The current build script was to make AppVeyor happy which installs OpenCV through `choco`.

**Comment by Pzixel** [comment]
@nebgnahz AppVeyor is happy because you have specified exact version of `OpenCV` in your script. But users are likely to install the newest version, I am one of them. You have either fix specific version in the readme, e.g. `This library is working with OpenCV v3.3 only` or enhance discovery mechanism to enable multiversioning support, It doesn't seem very complicated because exe pattern is just `opencv_worldxxx.dll`.
`, and it's unlikely that something breaks in new version but

**Comment by nebgnahz** [comment]
Ok, I see; looking forward to your PR.

**Comment by Pzixel** [comment]
https://github.com/nebgnahz/cv-rs/pull/27/files
