### ISSUE TITLE
Mat::image_encode is leaking

### ISSUE THREAD

**Issue by vstepchik** [nebgnahz/cv-rs#83]
Hi! Thank you very much for the bindings!

I'm trying to save frames from a video stream as JPEG files, however, as soon as I uncomment the line
`let bytes = mat.image_encode(".jpg", vec![])?;` the app starts consuming more and more memory until it gets OOM-killed.

```rust
extern crate cv;
use cv::*;
use cv::highgui::{Show, WindowFlag};
use cv::imgcodecs::ImageWriteMode;
use std::fs::File;
use std::io::prelude::*;
use std::error::Error;

const WINDOW_NAME: &'static str = "smile";

fn main() -> Result<(), Box<Error>> {
    let capture = videoio::VideoCapture::new(0);
    let window = cv::highgui::highgui_named_window(WINDOW_NAME, WindowFlag::Opengl);

    while capture.is_open() {
        let mat = capture.read();
        if let Some(mat) = mat {
            mat.show(WINDOW_NAME, 50);
//            let bytes = mat.image_encode(".jpg", vec![])?;
//            File::create("img.jpg")?.write_all(bytes.as_slice())?;
        } else {
            break
        }
    }
    Ok(())
}
```

Could you please explain to me what I'm doing wrong or confirm if it is a bug?
Using OpenCV 3.4.1 with GStreamer on rust 1.28.0-nightly.

**Comment by Pzixel** [comment]
Hey there!

Can you please share CMake flags you used to build the opencv so I could reproduce?

**Comment by vstepchik** [comment]
I'm using the opencv-gstreamer package from AUR: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opencv-gstreamer

**Comment by Pzixel** [comment]
Yep, it seems that the problem is with `ImencodeResult` which has C-allocated memory which gets copied into Rust one:

https://github.com/nebgnahz/cv-rs/blob/master/src/imgcodecs.rs#L143

but never gets freed.

**Comment by Pzixel** [comment]
Well, there is actually a comment 😄 
https://github.com/nebgnahz/cv-rs/blob/master/native/imcodecs.cc#L18

**Comment by vstepchik** [comment]
Is there anything I could help with?

**Comment by Pzixel** [comment]
@vstepchik well, there is a branch where the fix is located: https://github.com/nebgnahz/cv-rs/tree/feature/leak_fix

Unfortunately, it's currently fails with segfault while I cannot debug it on windows for several reasons. So you have to wait until I get home and up my ubuntu VM or you can try to locate it yourself.

**Comment by Pzixel** [comment]
@nebgnahz any idea why CI fails?

```
+ cd /home/travis/build/nebgnahz/cv-rs/opencv-3.4.1/build
++ pwd
+ echo 'Configuring at /home/travis/build/nebgnahz/cv-rs/opencv-3.4.1/build'
Configuring at /home/travis/build/nebgnahz/cv-rs/opencv-3.4.1/build
+ cmake -D WITH_CUDA=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_java=OFF -D BUILD_opencv_python=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D OPENCV_EXTRA_MODULES_PATH=/home/travis/build/nebgnahz/cv-rs/opencv_contrib-3.4.1/modules -D CMAKE_INSTALL_PREFIX=/home/travis/usr -D CMAKE_BUILD_TYPE=Release -D CUDA_ARCH_BIN=5.2 -D CUDA_ARCH_PTX= ..
CMake Error: The source directory "/home/travis/build/nebgnahz/cv-rs/opencv-3.4.1" does not appear to contain CMakeLists.txt.
```

I don't see why it says that source directory is `/home/travis/build/nebgnahz/cv-rs/opencv-3.4.1` when `pwd` is clearly `/home/travis/build/nebgnahz/cv-rs/opencv-3.4.1/build`

**Comment by vstepchik** [comment]
@Pzixel the fix works, it doesn't leak anymore, thank you!

**Comment by Pzixel** [comment]
@vstepchik ok, then I create a PR for it. Thank you for a report!

**Comment by nebgnahz** [comment]
> any idea why CI fails?

Fixing the CI now. There is nothing in `/home/travis/build/nebgnahz/cv-rs/opencv-3.4.1` after we use git submodules instead of downloading the zip.

**Comment by Pzixel** [comment]
Let's keep discussion in PR.
