### ISSUE TITLE
Filed to compile at Windows 10

### ISSUE THREAD

**Issue by hajsf** [nebgnahz/cv-rs#94]
I got the below error:

```
Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\cv>cargo build
   Compiling cv v0.2.2 (https://github.com/nebgnahz/cv-rs.git#bdbca2f3)
error: failed to run custom build command for `cv v0.2.2 (https://github.com/nebgnahz/cv-rs.git#bdbca2f3)`
process didn't exit successfully: `D:\cv\cv\target\debug\build\cv-f3f9003a4e5663ab\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-pc-windows-msvc")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\mat.o" "/c" "native\\mat.cc"
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\highgui.o" "/c" "native\\highgui.cc"
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\features2d.o" "/c" "native\\features2d.cc"
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\common-rust.o" "/c" "native\\common-rust.cc"
mat.cc
highgui.cc
features2d.cc
common-rust.cc
c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\highgui.h(4): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directoryc:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory

c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
exit code: 2
exit code: 2
exit code: 2
exit code: 2

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\highgui.o" "/c" "native\\highgui.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).

', C:\Users\Hasan Yousef\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.25\src\lib.rs:2260:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Pzixel** [comment]
> c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directoryc:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory

You don't have properly installed `opencv`. You need to follow the instruction.

**Comment by hajsf** [comment]
@Pzixel 
I downloaded [downloaded](https://opencv.org/opencv-3-4-1.html) , Set the OpenCV enviroment variable and add it to the systems path as 
`setx -m OPENCV_DIR D:\OpenCV\Build\x64\vc10`
then added `%OPENCV_DIR%\bin` to the system path!
Anything else I've to do?

I installed `VS 2015` + `Win 10 SDK` + `CMAKE x64` + `Git` + `CUDA`
I copied the `.windows` folder to the root directory of my folder
I did not get the `.get` folder mentioned in the instructions 
run the `cargo build` again, and looks to be same:

> Microsoft Windows [Version 10.0.17134.345]
> (c) 2018 Microsoft Corporation. All rights reserved.
> 
> C:\Users\Hasan Yousef>d:
> 
> D:\>cd cv\cv
> 
> D:\cv\cv>cargo build
>    Compiling cv v0.2.2 (https://github.com/nebgnahz/cv-rs.git#bdbca2f3)
> error: failed to run custom build command for `cv v0.2.2 (https://github.com/nebgnahz/cv-rs.git#bdbca2f3)`
> process didn't exit successfully: `D:\cv\cv\target\debug\build\cv-f3f9003a4e5663ab\build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-pc-windows-msvc")
> OPT_LEVEL = Some("0")
> HOST = Some("x86_64-pc-windows-msvc")
> CXX_x86_64-pc-windows-msvc = None
> CXX_x86_64_pc_windows_msvc = None
> HOST_CXX = None
> CXX = None
> CXXFLAGS_x86_64-pc-windows-msvc = None
> CXXFLAGS_x86_64_pc_windows_msvc = None
> HOST_CXXFLAGS = None
> CXXFLAGS = None
> DEBUG = Some("true")
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\highgui.o" "/c" "native\\highgui.cc"
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\mat.o" "/c" "native\\mat.cc"
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\imcodecs.o" "/c" "native\\imcodecs.cc"
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\common-rust.o" "/c" "native\\common-rust.cc"
> highgui.cc
> mat.cc
> imcodecs.cc
> common-rust.cc
> c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\highgui.h(4): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
> exit code: 2
> c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
> c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
> c:\users\hasan yousef\.cargo\git\checkouts\cv-rs-2ef8cae194ab26b5\bdbca2f\native\common.h(6): fatal error C1083: Cannot open include file: 'opencv2/core.hpp': No such file or directory
> exit code: 2
> exit code: 2
> exit code: 2
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "/nologo" "/MD" "/Z7" "/I" "native" "/I" "C:\\opencv\\build\\x64\\vc15\\include" "/W4" "/FoD:\\cv\\cv\\target\\debug\\build\\cv-2beb3f0be34e2c08\\out\\native\\highgui.o" "/c" "native\\highgui.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).
> 
> ', C:\Users\Hasan Yousef\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.25\src\lib.rs:2260:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> 
> D:\cv\cv>

My directory structure is as below:

> D:\cv\cv>dir
>  Volume in drive D is Data
>  Volume Serial Number is 2C2D-075A
> 
>  Directory of D:\cv\cv
> 
> 10/17/2018  02:32 PM    <DIR>          .
> 10/17/2018  02:32 PM    <DIR>          ..
> 10/17/2018  07:54 AM                19 .gitignore
> 10/17/2018  02:32 PM    <DIR>          .windows
> 10/17/2018  12:32 PM            13,599 Cargo.lock
> 10/17/2018  07:56 AM               138 Cargo.toml
> 10/17/2018  07:54 AM    <DIR>          src
> 10/17/2018  12:33 PM    <DIR>          target
>                3 File(s)         13,756 bytes
>                5 Dir(s)  50,852,802,560 bytes free

**Comment by Pzixel** [comment]
You shouldn't download anything automatically since it's done via scripts.

You need to compile opencv from source because it's how Rust wraps the C code.
Downloading `opencv` source code won't help either because some dependencies require `opencv_contrib` to be there.

So, you just have to follow the instruction. `.git` is a hidden folder in the repo root (with `.windows` one), which is required to restore the correct version of the `opencv`. Without it all subsequent steps will obviosly fail.

So, you have to copy both folders and then continue following the instruction. Scripts should do everything for you. You can test opencv is properly installed via running `opencv_version`. It should return version number:
![image](https://user-images.githubusercontent.com/11201122/47152062-3cd88780-d2e4-11e8-9ee2-46c3c401aaa4.png)

Before running `cargo build` you have to correctly follow the instruction and run powershell scripts that configures opencv for you.

**Comment by hajsf** [comment]
It looks I'm unable to install (or do not know how to install) OpenCV from source code, I did what is mentioned [here](https://perso.uclouvain.be/allan.barrea/opencv/cmake_config.html), but `opencv_version` show nothing (no internal or external command)

<img width="769" alt="cmake_14" src="https://user-images.githubusercontent.com/26045838/47252323-6eb82e00-d44b-11e8-95ab-670355c139f1.PNG">

**Comment by hajsf** [comment]
Appreciate if you can help me with [this](https://stackoverflow.com/questions/52903681/how-can-i-compile-opencv-from-source-at-win-10) it looks I stuck.

**Comment by Pzixel** [comment]
You don't have to run anything except scripts... Why do you manually open `CMake`? There is nothing about it in instruction. You just have to copy two folders and run one script (or two if you need CUDA).

**Comment by Pzixel** [comment]
Copy two directories:

![image](https://user-images.githubusercontent.com/11201122/47254095-bd72c180-d465-11e8-8b6e-a5599168eed3.png)

Then do
```
git reset --hard
git submodule update
```

You will see something like:

![image](https://user-images.githubusercontent.com/11201122/47254229-ef852300-d467-11e8-8821-7da92749d794.png)

Then run 
```ps
PowerShell -NoExit -File (.\.windows\msvc_2_build_OCV.ps1 -EnableCuda $False -Compiler vc15)
```

It should run the script and configure opencv.

P.S.
If you have error `cmake is not recognised` add `C:\Program Files\CMake\bin` to the PATH.

**Comment by hajsf** [comment]
Upon running `git submodule update` I did not get anything, kindly see below screen shot:

<img width="815" alt="ps" src="https://user-images.githubusercontent.com/26045838/47255969-17cd4b80-d481-11e8-9cd5-fdc898648195.PNG">

**Comment by hajsf** [comment]
Is not `vc15` if for `VS2017`, I understood it will not compile with it, and will compile only with `VS2015` which is `vc14`, is there something wrong in my understanding

**Comment by Pzixel** [comment]
All screenshots above are for VS2017 (vc15). If you have 2015 it's clearly vc14 as mentioned in instruction.

Sorry, I didn't see you use 2015.

**Comment by Pzixel** [comment]
This sentence was valid when I wrote it. Things may change, but I don't see how you get that it's now supported.

You can either use vc14 with Cuda on or off, or vc15 with cuda off. Choose what you like more. I'm not sure you need CUDA at all so just use any compiler (vc14 or vc15) and set CUDA off. If you need it then you have to install it beforehand. It's mentioned as an optional step in instruction.

**Comment by hajsf** [comment]
Thanks, it is clear now, it looks I did not understand the documentation properly.

Can you pls help with this: https://users.rust-lang.org/t/working-with-vision-control/21339
